# Generated by Django 3.2.9 on 2021-12-22 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('img', models.URLField(blank=True, null=True)),
                ('year', models.SmallIntegerField(default=0)),
                ('ua', models.SmallIntegerField(blank=True, null=True)),
                ('seasons', models.SmallIntegerField(blank=True, default=1)),
                ('poster', models.URLField(blank=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('casts', models.ManyToManyField(blank=True, related_name='casts', to='api.Cast')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video', models.CharField(max_length=1000)),
                ('private', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('header', models.CharField(blank=True, max_length=100)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='api.drama')),
            ],
        ),
        migrations.AddField(
            model_name='drama',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='api.Genre'),
        ),
    ]
